limit: 1000 #limit of blocks
delay: 30 #in minutes, how often to run a lagcheck
materials:  #materials counted as part of a lag machine
   - REDSTONE_WIRE
   - PISTON_BASE
   - PISTON_EXTENSION
   - PISTON_STICKY_BASE
   - REDSTONE_TORCH_ON
   - REDSTONE_TORCH_OFF
   - OBSERVER
   - REDSTONE_BLOCK
   - PISTON_MOVING_PIECE
   - REDSTONE_COMPARATOR
   - REDSTONE_COMPARATOR_OFF
   - REDSTONE_COMPARATOR_ON
   - DIODE
   - DIODE_BLOCK_OFF
   - DIODE_BLOCK_ON
   - SLIME_BLOCK